### ISSUE TITLE
German Translation Help!

### ISSUE THREAD

**Issue by PoloqTV** [TheWhisp/android_device_samsung_a5ultexx#1]
Hey TheWhisp!

Where can I find the (german translation.xml) to translate from English to German?
I have some translation errors found and some texts are not in German.
Would like to translate and help you so, i hope it is okay? 

Greets from Germany!

Contact: Proloq.info@googlemail.com

**Comment by TheWhisp** [comment]
Hello!

The translation happens in CyanogenMod, I just port the ROM to the device.
Check the CyanogenMod Wiki, I think there should be some information about translating
