### ISSUE TITLE
Error flashing SM-A500FU with 'cm-13.0-20151231-UNOFFICIAL-a5ultexx.zip'

### ISSUE THREAD

**Issue by horus999** [TheWhisp/android_device_samsung_a5ultexx#11]
can you help me ?
thanks

[recovery.pdf](https://github.com/TheWhisp/android_device_samsung_a5ultexx/files/112541/recovery.pdf)

**Comment by TheWhisp** [comment]
Try formatting system before flashing the build

**Comment by horus999** [comment]
It worked
thanks
