### ISSUE TITLE
Touch input not working

### ISSUE THREAD

**Issue by ttrobisch** [TheWhisp/android_device_samsung_a5ultexx#15]
The Touchscreen is infrequently not taking inputs if you turn the screen on. I got this issue with the aicp mm and cm13 Roms by you.

**Comment by nenchi** [comment]
Gladly to read that I'm not the only one with this problem. And probably nothing wrong with my phone. It's happens to me right now, when I'm charching phone. It happens with previous versions of cm13 too (don't remember if was always at recharching). After that error I always reboot phone, clean cache and dalvik. I don't know if that helps for while. But for few days I didn't have problems with touchscreen.

**Comment by jplitza** [comment]
I have that problem too, in two variants:
- When using the _inactivity display_, for example after taking the phone out of my pocket, without pressing any buttons. Normally, swiping from the bottom brings up the unlock screen, but sometimes it doesn't accept any touch input. Pressing the power button to bring up the "real" lock screen solves the problem most of the time.
- When pressing a button to wake up. In this situation, nothing seems to help (not pressing the power button, not locking and unlocking again – though rebooting probably would work). I simply wait for some time (sometimes one minute, sometimes 15) and then it works again.

**Comment by TheWhisp** [comment]
should be fixed in the next builds.

**Comment by jplitza** [comment]
Don't know if it's still important then, but the 20160224 image made matters much worse. In one day testing, I had to reboot almost every time when I wanted to use my phone.

**Comment by TheWhisp** [comment]
the 20160224 introduced more problems (I found that out after I had already uploaded the build), but I have never had to reboot my device. Extract the attached file and push it to /system/priv-app/InputDisabler/. I haven't had any issues with it yet.

[InputDisabler.apk.tar.gz](https://github.com/TheWhisp/android_device_samsung_a5ultexx/files/149311/InputDisabler.apk.tar.gz)

**Comment by nenchi** [comment]
Thank you very much for fixing problems. I'm using version 20160224 for one day and I haven't any problems with touchscreen after locking device :D
