### ISSUE TITLE
VPN - Doesn't work

### ISSUE THREAD

**Issue by horus999** [TheWhisp/android_device_samsung_a5ultexx#16]
I'm writing to you because I have an A5 and I have a Rom cm-13.0-20160207-UNOFFICIAL-a5ultexx.zip installed.
I  can't make the VPN connection work (L2TP /Ipsec psk).
Can you help me?
Thanks in advance.
Regards,

**Comment by nenchi** [comment]
I successfully connected with vpn (L2TP/ipsec psk)
I tried one from here:
http://www.vpngate.net/en/

Here is even simple guide for theirs vpn settings:
http://www.vpngate.net/en/howto_l2tp.aspx#android

I believe this issue could be closed.

I'm using cm 13 from 12. march 2016 on A500FU.
