### ISSUE TITLE
Can't boot to recovery. 

### ISSUE THREAD

**Issue by Natrocx** [TheWhisp/android_device_samsung_a5ultexx#17]
After I have installed cm13 everything was working fine except from accessing the recovery. I held volume up + power as I was used to but the only message standing in the top left corner was : Kernel not SEAndroid enforcing. Set warranty bit : Kernel. 
I tried this several times but the phone now can only boot into download and the usual system (trying through software also wasn't successful). This happens on both the stock recovery and TWRP 2.8.7.0

**Comment by Natrocx** [comment]
Cm : 20160205-UNOFFICIAL

**Comment by ttrobisch** [comment]
You have to press the home button too.
Vol Up + Power + Home.
Reboot to recovery via software is not working atm.
