### ISSUE TITLE
headphones

### ISSUE THREAD

**Issue by ghost** [TheWhisp/android_device_samsung_a5ultexx#2]
If i plug headphones in my a5 it doesn't recognizes them and the sound come from the speaker.

**Comment by TheWhisp** [comment]
I use headphones everyday and I they work just fine.. please give more details

**Comment by ghost** [comment]
i have cyanogenmod 12.1 (CM-12.1-20151007-UNOFFICIAL-a5ulte.zip) with gapps (open_gapps-arm-5.1-nano-20151023.zip) and if i try to listen to music the sound exit from the speaker and not from the headphones. i hope now i was more specify.

**Comment by ghost** [comment]
i also tried to do a factory reset and reinstall the zip, but the problem persist

**Comment by TheWhisp** [comment]
There is no such issue on any of my builds, as I said I listen to music everyday and I have never experienced such issue
