### ISSUE TITLE
Can't reboot to custom recovery (TWRP)

### ISSUE THREAD

**Issue by com1234** [TheWhisp/android_device_samsung_a5ultexx#20]
I flash TWRP recovery following the instruction from [here](http://forum.xda-developers.com/samsung-a-series/orig-development/recovery-teamwin-recovery-project-twrp-t3182214) but after i try to reboot i can onle see the stock android recovery.
What's going on?

**Comment by TheWhisp** [comment]
Uncheck "auto reboot" and reboot manually when the installation is done

**Comment by com1234** [comment]
Ty to do. IT not help.
1 mar 2016 13:25 "Dāvis Mālnieks" notifications@github.com napisał(a):
