### ISSUE TITLE
Not repsond for touch

### ISSUE THREAD

**Issue by andrasfokt** [TheWhisp/android_device_samsung_a5ultexx#21]
Sometimes the phone doesn't respond for touch for few minutes.

SM-A500FU

**Comment by TheWhisp** [comment]
Please include more information. How to reproduce, on which build it happened etc.

**Comment by andrasfokt** [comment]
Version: 13.0-20160224-UNOFFICIAL-a5ultexx
- When the problem occurs?
- When I get a notification and I want to unlock my phone. Not always, but the problem comes out every 2-3 days.

**Comment by TheWhisp** [comment]
Update to the latest version
