### ISSUE TITLE
Showing slowly charging

### ISSUE THREAD

**Issue by nenchi** [TheWhisp/android_device_samsung_a5ultexx#22]
I don't know why it alway shows slowly charging. I tried with different phone charger, differrent language. I primary use slovenian. I really don't know why it's that. Does anybody has the same problem? If there is a way how can I change it? A5 normally charge it around 1 hour and 20-40 minutes.

**Comment by TheWhisp** [comment]
A5 has max charging at 1 000 000 micro amperes, and it is considered as slow charging
