### ISSUE TITLE
touch screen not working

### ISSUE THREAD

**Issue by txX123** [TheWhisp/android_device_samsung_a5ultexx#23]
Second time this happened first time 30 minutes no touch screen working. Buttons work but i cant even choose restart . Cant use button combo or hold power long time so it would restart. Currently stuck at lock screen. :( I wont use this rom anymore . Hopefully i can use the phone again

**Comment by nenchi** [comment]
Did you try to clean dalvik and cache in recovery? I have the latest custom rom from 12 march and I don't have problems with touch input. You can press and hold buttona Volume-+ power(lock/unlock) for like 5-10 second, and phone will forcely restart.

**Comment by txX123** [comment]
Yes i had the latest rom . I couldn't restart even using buttons. I flashed stock rom back .Bug lasted 30 minutes then i went to download mode restored stock. I used it more than 1 week first time i lost touch screen i played a game . Second time problem occurred i charged it to full could not open lock touch screen didnt work. I pressed power button but i could not choose restart. Holding just power button and volume didnt work either . Tried many times different button combos . Connected to computer it only showed battery connected??? Could not access to phones internal memory.

**Comment by nenchi** [comment]
It should restart it you press at the same time and hold Volume down and Power button for like 8seconds. It won't work with volume up. Did you try to shut down device, boot into recovery with holding buttons, Volume up, home button amd power, (power can be released after 3-5seconds, when samsung logo shows) but it will shows on top left screen kernel: recovery when will boot into recovery mode. Then you should try to wipe with advanced mode and choose dalvik and cache, then slide to wipe. If that wouldn't help. Then maybe you could try to save latest custom rom on sdcard, wipe dalvin, cache and system partition. But I will recommend to create backup of personal data with program like titanium backup or easy backup (this program make backups of contacts,messages,logs, but not settings in applications) before that. Maybe even in recovery mode with backup option, but you will need external sdcard. After you wiped dalvik,cache and system, don't reboot, just go back and install custom rom. I did this, and I don't have problems. But I have it with earliers version with touch input. I did this what whips says on the same problem with version from 24 februar on this site: https://github.com/TheWhisp/android_device_samsung_a5ultexx/issues/15
For usb storage options, you have to choose in notifications and tap on usb charge only, and than choose usb storage or something like that. You have to do this everytime you connet device to PC. You could access to internal memory via TWRP recovery mode. Just connect phone to computer, but you need to have installed drivers for usb. I hope it will help it.
