### ISSUE TITLE
Music volume way too loud after pause

### ISSUE THREAD

**Issue by dewil-official** [TheWhisp/android_device_samsung_a5ultexx#24]
Hey, 
I've got your awesome Rom on my A500FU, running latest version with Gapps and some apps. But using the standart music-app, after stopping the playback of some music, the volume will turn up completely for a couple of sec. when pressing on play. After that little shock-moment it works normally again, every time. (It happens EVERY time, resuming the playback)
Thanks for your awesome work, keep it up!

**Comment by TheWhisp** [comment]
does it happen only with the stock CyanogenMod music app? Do you use equalizer/audio effects?
There is no such issue with the music app I use.
