### ISSUE TITLE
GApps crashing

### ISSUE THREAD

**Issue by Dhalion** [TheWhisp/android_device_samsung_a5ultexx#27]
Hey,
The System itself works fine! But after flashing openGapps for 6.0 and ARM (Stock version) errors keep poppig up that any gapp has crashed and is closed now. Was I flashing the wrong GApps package?

Christopher

**Comment by Dhalion** [comment]
Sorry, forgot specs
Device: SM500FU
SYSTEM: cm_a5ultexx-userdebug 6.0.1 MHC19Q 897cd8c121 test-keys
GApps: open_gapps-arm-6.0-stock-20160425
Recovery: TWRP 2.8.7.0

**Comment by tomalexw** [comment]
You can solve the problem by fastly going in to settings, then to apps and click on the three points, then on show system, now you search for setup wizard and after that you click on permissions and then activate contacts and phone. Problem solved
