### ISSUE TITLE
the phone restarts when I call or get calls

### ISSUE THREAD

**Issue by fabioa991** [TheWhisp/android_device_samsung_a5ultexx#30]
when I call  my phone restarts and in i get calls it restarts and it doesn't works the touch screen

**Comment by TheWhisp** [comment]
Cannot reproduce.

**Comment by nenchi** [comment]
I have the same problem when I installed xposed and GravityBox. Solution for this was, remove GravityBox, and move apk in root/system/app/GravityBox/ (create new folder). You must do the same for update, just delete previous version in folder.
