### ISSUE TITLE
A500fu Restarts while making or receiving calls

### ISSUE THREAD

**Issue by shafqatmeh** [TheWhisp/android_device_samsung_a5ultexx#32]
everything else works great and i do get OTG support enabled but the only problem is that mobile restart while making or receiving calls, I have tried many times with different versions(12.1 and cm13) but same problem.

**Comment by TheWhisp** [comment]
Cannot reproduce

**Comment by shafqatmeh** [comment]
What do you mean? How can i get rid of this problem.

**Comment by TheWhisp** [comment]
It means there is no such issue, calls working fine here.

**Comment by shafqatmeh** [comment]
No it doesn't work. I have installed the official version again.
