### ISSUE TITLE
A500FU Restart while making call or receiving calls.

### ISSUE THREAD

**Issue by shafqatmeh** [TheWhisp/android_device_samsung_a5ultexx#33]
any solution?

**Comment by dmeic** [comment]
Problem is related to Gapps, use pico or nano package without Dialer app. Someone mentioned that selecting default Dialer app cures this but I haven't tested it.

**Comment by shafqatmeh** [comment]
Thank you friend I will try that again, do you have any link for that?
Thanks again for your time... :-)

**Comment by TheWhisp** [comment]
@shafqatmeh read what @dmeic wrote
