### ISSUE TITLE
TWRP:-patching system image unconditionally...  not fininsh

### ISSUE THREAD

**Issue by hqhlwz** [TheWhisp/android_device_samsung_a5ultexx#38]
Installation Problem
my device ：(china) SM-A5000  CPU:Qualcomm MSM8916 cortex-A53  GPU：Adreno 306  RAM:2G  16G
 flash cm-13.0-20151115-UNOFFICIAL-a5ultexx or cm-13.0-20160709-UNOFFICIAL-a5ultexx
TWRP:-patching system image unconditionally...
and  stop here  and  not fininsh ,how to fix it........thanks your  help

**Comment by TheWhisp** [comment]
That variant of the device is not supported
