### ISSUE TITLE
wifi discovery temporarily not functional cm13

### ISSUE THREAD

**Issue by ttrobisch** [TheWhisp/android_device_samsung_a5ultexx#7]
Everytime when I boot, its no problem to connect to a wifi. But when I leave the place of wifi 'A' and then go to the place where I want to log into wifi 'B', then wifi 'B' is not showing up in the settings menu. Even if i am connected to wifi 'a' and just disconnect for like 5 minutes because I am  out of range, it is not showing up or reconnecting to wifi 'a'.
If you explain how i can make a log file, containing info about this, then I would help you to solve this bug.
I dont know if its helpful: I recovered the used wifi login credentials which I backed up with titanium backup in aicp 5.1.

**Comment by ttrobisch** [comment]
The issue appeared only if you used the Telekom online manager APP which wasn't compatible to Android 6, sorry for the noise

**Comment by TheWhisp** [comment]
You were correct, there was an issue like that. But it is now fixed in the latest build
