### ISSUE TITLE
Camera-App crashes when switching to Video

### ISSUE THREAD

**Issue by abangemann** [TheWhisp/android_device_samsung_a5ultexx#8]
The camera app can be opened and used for taking Pictures.
But when i'm switching to Video the app chrashes and gets closed.
Im using a Galaxy A5 A500FU.
![photo_2016-01-05_15-57-45](https://cloud.githubusercontent.com/assets/7310461/12118130/1de23d08-b3c5-11e5-89c0-e7bf4b8ae75c.jpg)

**Comment by TheWhisp** [comment]
From the screen-shot it seems you are using the new Google Camera app which is officially supported for selected Nexus devices

**Comment by abangemann** [comment]
well, I just installed the GApps ("stock")
Is there any possibility to deinstall the Google camera?
